version: '3'
services:
  
  
### If you are using image: 'rabbitmq:3.6.1-management', then you required to run below commands within container name 'rabbitmq'
##rabbitmq-plugins enable rabbitmq_management
##rabbitmqctl add_user test test
##rabbitmqctl set_user_tags test administrator
##rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
  
#  rabbitmq-service:
#    image: rabbitmq:3.6.1-management
#    container_name: rabbitmq
#    volumes:
#      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
#      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
#      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
#    environment:
#      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
#    ports:
#      - 5672:5672
#      - 15672:15672
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq   
    
      
  customer-service:
    build: ./customer-service
    ports:
      - "5001:5001"
  
  order-service:
    build: ./order-service
    ports:
    #  - "5002:5002"
       - "5012-5020:5002"
  
  gateway-service:
    build: ./gateway-service
    ports:
      - "5003:5003"

  payment-service:
    build: ./payment-service
    ports:
      - "5005:5005"
 



           
#networks:
#  microservice-net:
#    driver: bridge
